/**
 * TtsPregenService
 *
 * Coordinates server-side TTS pre-generation for a plan:
 *   1. startPregen()  — called after plan activation (studio quality).
 *                       Enumerates TTS pairs, creates tts_jobs rows, and
 *                       dispatches a Lambda worker task (or setImmediate() locally).
 *   2. processJobs()  — called by the Lambda worker.
 *                       Synthesizes each job via TtsService and updates the DB.
 *
 * Local-dev mode (IS_LOCAL=true): uses setImmediate() instead of Lambda self-invocation.
 */
import { Injectable, Logger } from '@nestjs/common';
import {
  LambdaClient,
  InvokeCommand,
  InvocationType,
} from '@aws-sdk/client-lambda';
import { S3Client, HeadObjectCommand, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { DatabaseService } from '../database/database.service';
import { TtsService } from './tts.service';
import { TtsEnumerationService } from './tts-enumeration.service';
import type { TtsPregenWorkerTask } from '../lambda';

/** How many TTS jobs to dispatch per Lambda worker invocation. */
const CHUNK_SIZE = 10;

/** Pre-signed URL TTL in seconds (1 hour). */
const PRESIGN_TTL_SECONDS = 3600;

@Injectable()
export class TtsPregenService {
  private readonly logger = new Logger(TtsPregenService.name);
  private readonly s3: S3Client | null;
  private readonly bucket: string | null;
  private readonly lambda: LambdaClient | null;

  constructor(
    private readonly db: DatabaseService,
    private readonly ttsService: TtsService,
    private readonly enumService: TtsEnumerationService,
  ) {
    this.bucket = process.env.AWS_S3_BUCKET ?? null;
    this.s3 = this.bucket
      ? new S3Client({ region: process.env.AWS_REGION ?? 'ap-south-1' })
      : null;

    const functionName = process.env.AWS_LAMBDA_FUNCTION_NAME;
    this.lambda =
      functionName && !process.env.IS_LOCAL
        ? new LambdaClient({ region: process.env.AWS_REGION ?? 'ap-south-1' })
        : null;
  }

  /**
   * Begin TTS pre-generation for a plan.
   * Called after plan activation with voiceQuality='studio'.
   */
  async startPregen(
    planId: string,
    planJson: string,
    voiceId: string,
    locale: string,
    provider: string,
    speechRate: string,
  ): Promise<void> {
    this.logger.log(`startPregen — planId=${planId}, provider=${provider}`);

    const pairs = this.enumService.enumerate(planJson, voiceId, locale, provider, speechRate);

    if (pairs.length === 0) {
      this.logger.warn(`startPregen — no TTS pairs found for planId=${planId}, marking complete`);
      await this.db.setTtsStatus(planId, 'completed', 0, 0);
      return;
    }

    // Create job records in DB.
    const jobRecords = await this.db.createTtsJobs(
      pairs.map((p) => ({
        planId,
        cacheKey: p.cacheKey,
        text: p.text,
        voiceId: p.voiceId,
        locale: p.locale,
        provider: p.provider,
        speechRate: p.speechRate,
      })),
    );

    await this.db.setTtsStatus(planId, 'processing', jobRecords.length, 0);
    this.logger.log(`startPregen — created ${jobRecords.length} jobs for planId=${planId}`);

    // Dispatch worker(s) — chunked to stay within Lambda payload/timeout limits.
    const jobIds = jobRecords.map((j) => j.id);
    for (let i = 0; i < jobIds.length; i += CHUNK_SIZE) {
      const chunk = jobIds.slice(i, i + CHUNK_SIZE);
      const task: TtsPregenWorkerTask = { task: 'ttsPregen', planId, jobIds: chunk };
      await this.dispatchWorker(task);
    }
  }

  /**
   * Process a batch of TTS jobs (called by the Lambda worker task handler).
   * Synthesizes each job, uploads audio to S3, and updates job + plan status.
   */
  async processJobs(planId: string, jobIds: string[]): Promise<void> {
    this.logger.log(`processJobs — planId=${planId}, jobs=${jobIds.length}`);

    const jobs = await this.db.getTtsJobsByIds(jobIds);

    for (const job of jobs) {
      try {
        // Check S3 first — may have been pre-generated by a previous run.
        const s3Key = `tts/${job.cacheKey}.wav`;
        const alreadyExists = await this.checkS3Exists(s3Key);

        if (!alreadyExists) {
          const audio = await this.ttsService.synthesize(
            job.text,
            job.voiceId,
            job.locale,
            job.provider,
            job.speechRate,
          );

          if (this.s3 && this.bucket) {
            await this.s3.send(
              new PutObjectCommand({
                Bucket: this.bucket,
                Key: s3Key,
                Body: audio,
                ContentType: 'audio/wav',
              }),
            );
          }
        }

        await this.db.updateTtsJobStatus(job.id, 'completed', s3Key);
        await this.db.incrementTtsCompleted(planId);
        this.logger.log(`processJobs — job ${job.id} completed (${job.cacheKey.slice(0, 12)}…)`);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        this.logger.error(`processJobs — job ${job.id} failed: ${msg}`);
        await this.db.updateTtsJobStatus(job.id, 'failed', undefined, msg);
      }
    }

    // Check whether all jobs for this plan are now done.
    const status = await this.db.getPlanTtsStatus(planId);
    const allDone = status.completed + status.failed >= status.total;
    if (allDone) {
      await this.db.finalizePlanTtsStatus(planId);
      this.logger.log(`processJobs — planId=${planId} finalized (${status.completed}/${status.total})`);
    }
  }

  /**
   * Get TTS pre-generation status for a plan.
   */
  async getStatus(planId: string) {
    return this.db.getPlanTtsStatus(planId);
  }

  /**
   * Get pre-signed S3 audio URLs for all completed TTS jobs of a plan.
   * Returns an empty map when S3 is not configured.
   */
  async getAudioUrls(planId: string): Promise<Record<string, string>> {
    if (!this.s3 || !this.bucket) {
      this.logger.warn(`getAudioUrls — S3 not configured, returning empty map for planId=${planId}`);
      return {};
    }

    const jobs = await this.db.getCompletedTtsJobs(planId);
    const urlMap: Record<string, string> = {};

    await Promise.all(
      jobs.map(async (job) => {
        if (!job.s3Key) return;
        try {
          const url = await getSignedUrl(
            this.s3!,
            new GetObjectCommand({ Bucket: this.bucket!, Key: job.s3Key }),
            { expiresIn: PRESIGN_TTL_SECONDS },
          );
          urlMap[job.cacheKey] = url;
        } catch (err) {
          this.logger.warn(
            `getAudioUrls — presign failed for job ${job.id}: ${err instanceof Error ? err.message : err}`,
          );
        }
      }),
    );

    this.logger.log(`getAudioUrls — returning ${Object.keys(urlMap).length} URLs for planId=${planId}`);
    return urlMap;
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  private async checkS3Exists(key: string): Promise<boolean> {
    if (!this.s3 || !this.bucket) return false;
    try {
      await this.s3.send(new HeadObjectCommand({ Bucket: this.bucket, Key: key }));
      return true;
    } catch {
      return false;
    }
  }

  private async dispatchWorker(task: TtsPregenWorkerTask): Promise<void> {
    if (process.env.IS_LOCAL) {
      // Local dev: process asynchronously in-process via setImmediate().
      this.logger.log(
        `dispatchWorker (local) — planId=${task.planId}, jobs=${task.jobIds.length}`,
      );
      setImmediate(() => {
        this.processJobs(task.planId, task.jobIds).catch((err) =>
          this.logger.error(`dispatchWorker setImmediate error: ${err instanceof Error ? err.message : err}`),
        );
      });
      return;
    }

    // Production: self-invoke this Lambda asynchronously.
    const functionName = process.env.AWS_LAMBDA_FUNCTION_NAME;
    if (!functionName || !this.lambda) {
      this.logger.warn('dispatchWorker — AWS_LAMBDA_FUNCTION_NAME not set, falling back to setImmediate()');
      setImmediate(() => {
        this.processJobs(task.planId, task.jobIds).catch((err) =>
          this.logger.error(`dispatchWorker fallback error: ${err instanceof Error ? err.message : err}`),
        );
      });
      return;
    }

    await this.lambda.send(
      new InvokeCommand({
        FunctionName: functionName,
        InvocationType: InvocationType.Event, // async, fire-and-forget
        Payload: Buffer.from(JSON.stringify(task)),
      }),
    );
    this.logger.log(
      `dispatchWorker — invoked Lambda ${functionName} for planId=${task.planId}, jobs=${task.jobIds.length}`,
    );
  }
}
