import type { Metadata } from 'next';
import DeletionForm from '@/components/DeletionForm';

// ────────────────────────────────────────────────────────────────────────────
// Metadata
// ────────────────────────────────────────────────────────────────────────────

export const metadata: Metadata = {
  title: 'Data Deletion Request',
  description:
    'Request deletion of your Instructor account data. We process all requests within 30 days in accordance with GDPR Article 17.',
  alternates: {
    canonical: '/data-deletion',
  },
  openGraph: {
    title: 'Data Deletion Request | Instructor',
    description:
      'Request deletion of your Instructor account data. GDPR-compliant processing within 30 days.',
    url: '/data-deletion',
    type: 'website',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Instructor — Data Deletion Request',
      },
    ],
  },
};

// ────────────────────────────────────────────────────────────────────────────
// Deletion consequences — shown in the informational section
// ────────────────────────────────────────────────────────────────────────────

const DELETION_CONSEQUENCES = [
  {
    id: 'account',
    icon: '👤',
    title: 'Account removed',
    description:
      'Your user account and login credentials will be permanently deleted. You will no longer be able to sign in.',
  },
  {
    id: 'plans',
    icon: '📋',
    title: 'Plans deleted',
    description:
      'All workout, meditation, study, and cooking plans you have created or saved will be permanently erased.',
  },
  {
    id: 'tts-cache',
    icon: '🔊',
    title: 'TTS cache purged',
    description:
      'All audio generated by the Kokoro TTS engine and stored in our cache will be removed from our servers.',
  },
  {
    id: 'tokens',
    icon: '🔑',
    title: 'Access tokens revoked',
    description:
      'All active API tokens and session tokens associated with your account will be immediately invalidated.',
  },
  {
    id: 'otp',
    icon: '📱',
    title: 'OTP data cleared',
    description:
      'Any pending one-time password records or device verification data linked to your account will be deleted.',
  },
] as const;

// ────────────────────────────────────────────────────────────────────────────
// Page component
// ────────────────────────────────────────────────────────────────────────────

/**
 * Data Deletion Request page — route: /data-deletion
 *
 * Displays the data deletion request process, consequences, and the
 * interactive DeletionForm component for submitting requests.
 */
export default function DataDeletionPage() {
  return (
    <div className="min-h-screen text-on-surface">
      {/* ── Page header ──────────────────────────────────────────────────── */}
      <section
        aria-labelledby="deletion-page-heading"
        className="mb-10 border-b border-outline-variant pb-10"
      >
        <h1
          id="deletion-page-heading"
          className="text-3xl font-extrabold text-primary mb-4"
        >
          Data Deletion Request
        </h1>
        <p className="text-base text-on-surface-variant max-w-2xl mb-4">
          You have the right to request deletion of your personal data at any
          time. This right is enshrined in{' '}
          <abbr title="General Data Protection Regulation">GDPR</abbr> Article 17
          (the &ldquo;right to erasure&rdquo;) and applicable data protection
          laws worldwide.
        </p>
        <div className="inline-flex items-center gap-2 rounded-lg bg-primary/10 px-4 py-3 text-sm font-medium text-primary">
          <svg
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          Requests are processed within <strong className="mx-1">30 days</strong> as
          required by GDPR Article 17.
        </div>
      </section>

      <div className="flex flex-col lg:flex-row gap-12">
        {/* ── Left column: consequences + process ──────────────────────── */}
        <aside className="lg:w-1/2 xl:w-5/12">
          {/* What will be deleted */}
          <section aria-labelledby="consequences-heading" className="mb-10">
            <h2
              id="consequences-heading"
              className="text-xl font-bold text-on-surface mb-2"
            >
              What gets deleted
            </h2>
            <p className="text-sm text-on-surface-variant mb-5">
              Depending on the scope you choose, the following data categories
              will be <strong>permanently and irreversibly</strong> removed:
            </p>

            <ul className="space-y-4" aria-label="Data deletion consequences">
              {DELETION_CONSEQUENCES.map((item) => (
                <li
                  key={item.id}
                  className="flex items-start gap-4 rounded-xl border border-outline-variant p-4"
                >
                  <span
                    className="text-2xl leading-none mt-0.5"
                    aria-hidden="true"
                  >
                    {item.icon}
                  </span>
                  <div>
                    <p className="text-sm font-semibold text-on-surface">
                      {item.title}
                    </p>
                    <p className="text-xs text-on-surface-variant mt-1">
                      {item.description}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
          </section>

          {/* How the process works */}
          <section
            aria-labelledby="process-heading"
            className="rounded-xl bg-primary/5 border border-primary/20 p-6"
          >
            <h2
              id="process-heading"
              className="text-base font-bold text-primary mb-4"
            >
              How the process works
            </h2>
            <ol className="space-y-3 list-none">
              {[
                {
                  step: '1',
                  text: 'Submit the form with your registered email address and choose which data to delete.',
                },
                {
                  step: '2',
                  text: 'Our team verifies the request and sends a confirmation email to the address provided.',
                },
                {
                  step: '3',
                  text: 'We process the deletion within 30 days and notify you once complete.',
                },
              ].map(({ step, text }) => (
                <li key={step} className="flex items-start gap-3">
                  <span
                    aria-hidden="true"
                    className="flex-shrink-0 w-7 h-7 rounded-full bg-primary text-white text-xs font-bold flex items-center justify-center"
                  >
                    {step}
                  </span>
                  <p className="text-sm text-on-surface-variant pt-0.5">{text}</p>
                </li>
              ))}
            </ol>
            <p className="mt-4 text-xs text-on-surface-variant">
              For questions or urgent requests contact{' '}
              <a
                href="mailto:admin@layersiq.com"
                className="underline hover:text-primary transition-colors min-h-[44px] inline-flex items-center"
              >
                admin@layersiq.com
              </a>
              .
            </p>
          </section>
        </aside>

        {/* ── Right column: form ────────────────────────────────────────── */}
        <section
          aria-labelledby="form-heading"
          className="lg:w-1/2 xl:w-7/12"
        >
          <h2
            id="form-heading"
            className="text-xl font-bold text-on-surface mb-6"
          >
            Submit your request
          </h2>

          {/* Warning notice */}
          <div
            role="note"
            className="mb-6 flex items-start gap-3 rounded-lg border border-warning bg-warning-container/30 p-4 text-on-surface"
          >
            <svg
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
              className="flex-shrink-0 mt-0.5 text-warning"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
              />
            </svg>
            <p className="text-sm">
              <strong>This action cannot be undone.</strong> Once your data is
              deleted it cannot be recovered. Download any data you wish to keep
              before submitting.
            </p>
          </div>

          <DeletionForm />
        </section>
      </div>
    </div>
  );
}
